// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlogPost = "blog_posts"

// BlogPost mapped from table <blog_posts>
type BlogPost struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title          string    `gorm:"column:title;not null" json:"title"`
	Content        string    `gorm:"column:content;not null" json:"content"`
	CoverImagePath string    `gorm:"column:cover_image_path" json:"cover_image_path"`
	CreatedBy      int64     `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName BlogPost's table name
func (*BlogPost) TableName() string {
	return TableNameBlogPost
}
